---
# indclude the type file for RHEL 8 type machines

- hosts: "{{ systems }}"
  become: yes
  become_method: sudo
  roles:
    - cis_security
  vars_prompt:
  - name: systems
    prompt: "Please write hosts or groupname"
    private: no
