---
- hosts: "{{ systems }}"
  become: yes
  become_method: sudo 
  roles:
    - ansible-role-clamav

  vars_prompt:
    - name: systems
      prompt: "Please write hosts or groupname"
      private: no

