- name: Update sshd_config
  hosts: PCI
  become: yes
  tasks:
    - name: Set ClientAliveInterval 300
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?ClientAliveInterval 900'
        line: 'ClientAliveInterval 300'
        state: present
        backup: yes
