---
- hosts: "{{ systems }}"
  become: yes
  gather_facts: no
  become_method: sudo
  tasks:
    - name: Ensure NTP (for time synchronization) is installed.
      yum: name=chrony state=present
    - name: Ensure NTP is running.
      service: name=chronyd state=started enabled=yes
    - name: Copy over the NTP configuration
      template: src=./templates/chrony.conf dest=/etc/chrony.conf
      # notify:
      #  - restart ntpd
      #    - lineinfile:
      #   path: /etc/chrony.conf
      #  regexp: '^pool'
      #  line: server 10.10.55.50 iburst
    - service:
        name: chronyd
        state: restarted


          #handlers:
            #  - name: restart ntpd
            # service: name=chronyd state=restarted

  vars_prompt:
    - name: systems
      prompt: "Please specify system or group names"
      private: no

