- name: Update sshd_config
  hosts: PCI
  become: yes
  tasks:
    - name: Set PermitEmptyPasswords no
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitEmptyPasswords'
        line: 'PermitEmptyPasswords no'
        state: present
        backup: yes

