---
- hosts: "{{systems}}"
  become: yes
  become_method: sudo
  roles:
    - roles/ansible-wazuh-agent
  vars:
    wazuh_managers:
      - address: 10.10.55.203
        port: 1514
        protocol: tcp
        api_port: 55000
        api_proto: 'http'
        api_user: ansible
        max_retries: 5
        retry_interval: 5
  vars_prompt:
    - name: systems
      prompt: "Please specify system or group names"
      private: no
      
